name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
      - run: cargo build --release --all --verbose --target=thumbv7em-none-eabihf

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
      - run: cargo test --verbose --all
